import type { SeedBird } from "./birds";

/** Original curated set (20). */
export const SEED_BIRDS_ORIGINAL: SeedBird[] = [
  {
    slug: "northern-cardinal",
    name: "Northern Cardinal",
    scientificName: "Cardinalis cardinalis",
    region: "Eastern North America",
    habitat: "Woodland edges, gardens, and shrublands",
    wikiTitle: "Northern cardinal",
  },
  {
    slug: "american-goldfinch",
    name: "American Goldfinch",
    scientificName: "Spinus tristis",
    region: "North America",
    habitat: "Weedy fields, meadows, and open floodplains",
    wikiTitle: "American goldfinch",
  },
  {
    slug: "blue-jay",
    name: "Blue Jay",
    scientificName: "Cyanocitta cristata",
    region: "Eastern North America",
    habitat: "Mixed and deciduous forests, suburban yards",
    wikiTitle: "Blue jay",
  },
  {
    slug: "european-robin",
    name: "European Robin",
    scientificName: "Erithacus rubecula",
    region: "Europe",
    habitat: "Woodlands, hedgerows, parks, and gardens",
    wikiTitle: "European robin",
  },
  {
    slug: "atlantic-puffin",
    name: "Atlantic Puffin",
    scientificName: "Fratercula arctica",
    region: "North Atlantic",
    habitat: "Coastal cliffs and open ocean",
    wikiTitle: "Atlantic puffin",
  },
  {
    slug: "greater-flamingo",
    name: "Greater Flamingo",
    scientificName: "Phoenicopterus roseus",
    region: "Africa, southern Europe, and Asia",
    habitat: "Saline lagoons, mudflats, and shallow lakes",
    wikiTitle: "Greater flamingo",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/0/07/Phoenicopterus_roseus_Luc_Viatour.jpg",
  },
  {
    slug: "indian-peafowl",
    name: "Indian Peafowl",
    scientificName: "Pavo cristatus",
    region: "Indian subcontinent",
    habitat: "Open forest and farmland near water",
    wikiTitle: "Indian peafowl",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/f/f5/Male_Pavo_cristatus_displaying_-_Peafowl_1.jpg",
  },
  {
    slug: "scarlet-macaw",
    name: "Scarlet Macaw",
    scientificName: "Ara macao",
    region: "Central and South America",
    habitat: "Humid lowland rainforest",
    wikiTitle: "Scarlet macaw",
  },
  {
    slug: "resplendent-quetzal",
    name: "Resplendent Quetzal",
    scientificName: "Pharomachrus mocinno",
    region: "Central America",
    habitat: "Cloud forests of southern Mexico to Panama",
    wikiTitle: "Resplendent quetzal",
  },
  {
    slug: "lilac-breasted-roller",
    name: "Lilac-breasted Roller",
    scientificName: "Coracias caudatus",
    region: "Sub-Saharan Africa",
    habitat: "Open woodland and savanna",
    wikiTitle: "Lilac-breasted roller",
  },
  {
    slug: "mandarin-duck",
    name: "Mandarin Duck",
    scientificName: "Aix galericulata",
    region: "East Asia",
    habitat: "Wooded ponds, lakes, and slow rivers",
    wikiTitle: "Mandarin duck",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/c/c0/Aix_galericulata_%28Male%29%2C_Richmond_Park%2C_UK_-_May_2013.jpg",
  },
  {
    slug: "common-kingfisher",
    name: "Common Kingfisher",
    scientificName: "Alcedo atthis",
    region: "Eurasia and North Africa",
    habitat: "Clear, slow-moving streams and rivers",
    wikiTitle: "Common kingfisher",
  },
  {
    slug: "keel-billed-toucan",
    name: "Keel-billed Toucan",
    scientificName: "Ramphastos sulfuratus",
    region: "Central and South America",
    habitat: "Tropical and subtropical rainforest",
    wikiTitle: "Keel-billed toucan",
  },
  {
    slug: "painted-bunting",
    name: "Painted Bunting",
    scientificName: "Passerina ciris",
    region: "Southern North America",
    habitat: "Thickets, woodland edges, and brush",
    wikiTitle: "Painted bunting",
  },
  {
    slug: "golden-pheasant",
    name: "Golden Pheasant",
    scientificName: "Chrysolophus pictus",
    region: "Western China",
    habitat: "Dense forests and bamboo thickets",
    wikiTitle: "Golden pheasant",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/b/bd/Ma_-_Male_Chrysolophus_pictus_-_1.jpg",
  },
  {
    slug: "rainbow-lorikeet",
    name: "Rainbow Lorikeet",
    scientificName: "Trichoglossus moluccanus",
    region: "Australia",
    habitat: "Rainforest, woodland, and urban gardens",
    wikiTitle: "Rainbow lorikeet",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/9/94/Rainbow_lorikeet_%28Trichoglossus_moluccanus_moluccanus%29_Adelaide_2.jpg",
  },
  {
    slug: "bohemian-waxwing",
    name: "Bohemian Waxwing",
    scientificName: "Bombycilla garrulus",
    region: "Northern Hemisphere",
    habitat: "Boreal forests and berry-rich woodlands",
    wikiTitle: "Bohemian waxwing",
  },
  {
    slug: "eurasian-hoopoe",
    name: "Eurasian Hoopoe",
    scientificName: "Upupa epops",
    region: "Europe, Asia, and Africa",
    habitat: "Open farmland, orchards, and grassland",
    wikiTitle: "Eurasian hoopoe",
  },
  {
    slug: "wood-duck",
    name: "Wood Duck",
    scientificName: "Aix sponsa",
    region: "North America",
    habitat: "Wooded swamps, marshes, and ponds",
    wikiTitle: "Wood duck",
  },
  {
    slug: "superb-starling",
    name: "Superb Starling",
    scientificName: "Lamprotornis superbus",
    region: "East Africa",
    habitat: "Savanna, open woodland, and lakeshores",
    wikiTitle: "Superb starling",
  },
];

/** Extended catalog — visually rich species for palette discovery. */
export const SEED_BIRDS_EXTENDED: SeedBird[] = [
  // Parrots & cockatoos
  {
    slug: "blue-and-yellow-macaw",
    name: "Blue-and-yellow Macaw",
    scientificName: "Ara ararauna",
    region: "South America",
    habitat: "Tropical rainforest and savanna",
    wikiTitle: "Blue-and-yellow macaw",
  },
  {
    slug: "hyacinth-macaw",
    name: "Hyacinth Macaw",
    scientificName: "Anodorhynchus hyacinthinus",
    region: "Central South America",
    habitat: "Palm savannas and gallery forest",
    wikiTitle: "Hyacinth macaw",
  },
  {
    slug: "blue-throated-macaw",
    name: "Blue-throated Macaw",
    scientificName: "Ara glaucogularis",
    region: "Bolivia",
    habitat: "Seasonally flooded savanna",
    wikiTitle: "Blue-throated macaw",
  },
  {
    slug: "military-macaw",
    name: "Military Macaw",
    scientificName: "Ara militaris",
    region: "Mexico to Argentina",
    habitat: "Mountain forest and arid woodland",
    wikiTitle: "Military macaw",
  },
  {
    slug: "sun-parakeet",
    name: "Sun Parakeet",
    scientificName: "Aratinga solstitialis",
    region: "Northern South America",
    habitat: "Savanna and forest edges",
    wikiTitle: "Sun parakeet",
  },
  {
    slug: "eclectus-parrot",
    name: "Eclectus Parrot",
    scientificName: "Eclectus roratus",
    region: "New Guinea and Australia",
    habitat: "Rainforest canopy",
    wikiTitle: "Eclectus parrot",
  },
  {
    slug: "galah",
    name: "Galah",
    scientificName: "Eolophus roseicapilla",
    region: "Australia",
    habitat: "Open woodland and grassland",
    wikiTitle: "Galah",
  },
  {
    slug: "major-mitchells-cockatoo",
    name: "Major Mitchell's Cockatoo",
    scientificName: "Lophochroa leadbeateri",
    region: "Australia",
    habitat: "Arid woodland and mallee",
    wikiTitle: "Major Mitchell's cockatoo",
  },
  {
    slug: "sulphur-crested-cockatoo",
    name: "Sulphur-crested Cockatoo",
    scientificName: "Cacatua galerita",
    region: "Australia and New Guinea",
    habitat: "Woodland, farmland, and urban areas",
    wikiTitle: "Sulphur-crested cockatoo",
  },
  {
    slug: "crimson-rosella",
    name: "Crimson Rosella",
    scientificName: "Platycercus elegans",
    region: "Eastern Australia",
    habitat: "Forest, woodland, and gardens",
    wikiTitle: "Crimson rosella",
  },
  {
    slug: "red-lory",
    name: "Red Lory",
    scientificName: "Eos bornea",
    region: "Indonesia",
    habitat: "Lowland rainforest",
    wikiTitle: "Red lory",
  },
  // Pheasants & pigeons
  {
    slug: "lady-amhersts-pheasant",
    name: "Lady Amherst's Pheasant",
    scientificName: "Chrysolophus amherstiae",
    region: "Southwestern China and Myanmar",
    habitat: "Dense forest and bamboo",
    wikiTitle: "Lady Amherst's pheasant",
  },
  {
    slug: "ring-necked-pheasant",
    name: "Ring-necked Pheasant",
    scientificName: "Phasianus colchicus",
    region: "Asia; introduced worldwide",
    habitat: "Farmland, grassland, and woodland edge",
    wikiTitle: "Ring-necked pheasant",
  },
  {
    slug: "temmincks-tragopan",
    name: "Temminck's Tragopan",
    scientificName: "Tragopan temminckii",
    region: "Eastern Himalayas and China",
    habitat: "Rhododendron and mixed forest",
    wikiTitle: "Temminck's tragopan",
  },
  {
    slug: "victoria-crowned-pigeon",
    name: "Victoria Crowned Pigeon",
    scientificName: "Goura victoria",
    region: "New Guinea",
    habitat: "Lowland rainforest",
    wikiTitle: "Victoria crowned pigeon",
  },
  {
    slug: "nicobar-pigeon",
    name: "Nicobar Pigeon",
    scientificName: "Caloenas nicobarica",
    region: "Andaman and Nicobar Islands to Pacific",
    habitat: "Coastal rainforest",
    wikiTitle: "Nicobar pigeon",
  },
  // Seabirds
  {
    slug: "blue-footed-booby",
    name: "Blue-footed Booby",
    scientificName: "Sula nebouxii",
    region: "Eastern Pacific",
    habitat: "Coastal cliffs and open ocean",
    wikiTitle: "Blue-footed booby",
  },
  {
    slug: "red-footed-booby",
    name: "Red-footed Booby",
    scientificName: "Sula sula",
    region: "Tropical oceans worldwide",
    habitat: "Coastal islands and atolls",
    wikiTitle: "Red-footed booby",
  },
  {
    slug: "magnificent-frigatebird",
    name: "Magnificent Frigatebird",
    scientificName: "Fregata magnificens",
    region: "Tropical Americas",
    habitat: "Coastal mangroves and open ocean",
    wikiTitle: "Magnificent frigatebird",
  },
  {
    slug: "toco-toucan",
    name: "Toco Toucan",
    scientificName: "Ramphastos toco",
    region: "South America",
    habitat: "Savanna and gallery forest",
    wikiTitle: "Toco toucan",
  },
  // North American songbirds
  {
    slug: "vermilion-flycatcher",
    name: "Vermilion Flycatcher",
    scientificName: "Pyrocephalus rubinus",
    region: "Americas",
    habitat: "Open woodland, scrub, and savanna",
    wikiTitle: "Vermilion flycatcher",
  },
  {
    slug: "summer-tanager",
    name: "Summer Tanager",
    scientificName: "Piranga rubra",
    region: "Americas",
    habitat: "Open deciduous and pine forest",
    wikiTitle: "Summer tanager",
  },
  {
    slug: "scarlet-tanager",
    name: "Scarlet Tanager",
    scientificName: "Piranga olivacea",
    region: "Eastern North America",
    habitat: "Mature deciduous forest",
    wikiTitle: "Scarlet tanager",
  },
  {
    slug: "western-tanager",
    name: "Western Tanager",
    scientificName: "Piranga ludoviciana",
    region: "Western North America",
    habitat: "Conifer and mixed forest",
    wikiTitle: "Western tanager",
  },
  {
    slug: "baltimore-oriole",
    name: "Baltimore Oriole",
    scientificName: "Icterus galbula",
    region: "Eastern North America",
    habitat: "Open woodland and forest edge",
    wikiTitle: "Baltimore oriole",
  },
  {
    slug: "bullocks-oriole",
    name: "Bullock's Oriole",
    scientificName: "Icterus bullockii",
    region: "Western North America",
    habitat: "Open woodland and riparian corridors",
    wikiTitle: "Bullock's oriole",
  },
  {
    slug: "red-winged-blackbird",
    name: "Red-winged Blackbird",
    scientificName: "Agelaius phoeniceus",
    region: "North America",
    habitat: "Marshes, wetlands, and grassland",
    wikiTitle: "Red-winged blackbird",
  },
  {
    slug: "prothonotary-warbler",
    name: "Prothonotary Warbler",
    scientificName: "Protonotaria citrea",
    region: "Eastern North America",
    habitat: "Bottomland forest and swamps",
    wikiTitle: "Prothonotary warbler",
  },
  {
    slug: "blackburnian-warbler",
    name: "Blackburnian Warbler",
    scientificName: "Setophaga fusca",
    region: "Eastern North America",
    habitat: "Conifer and mixed forest",
    wikiTitle: "Blackburnian warbler",
  },
  {
    slug: "american-redstart",
    name: "American Redstart",
    scientificName: "Setophaga ruticilla",
    region: "North America",
    habitat: "Deciduous and mixed forest",
    wikiTitle: "American redstart",
  },
  {
    slug: "indigo-bunting",
    name: "Indigo Bunting",
    scientificName: "Passerina cyanea",
    region: "North America",
    habitat: "Brushy edges and open woodland",
    wikiTitle: "Indigo bunting",
  },
  {
    slug: "lazuli-bunting",
    name: "Lazuli Bunting",
    scientificName: "Passerina amoena",
    region: "Western North America",
    habitat: "Brushy hillsides and riparian areas",
    wikiTitle: "Lazuli bunting",
  },
  {
    slug: "rose-breasted-grosbeak",
    name: "Rose-breasted Grosbeak",
    scientificName: "Pheucticus ludovicianus",
    region: "Eastern North America",
    habitat: "Deciduous and mixed forest",
    wikiTitle: "Rose-breasted grosbeak",
  },
  {
    slug: "black-headed-grosbeak",
    name: "Black-headed Grosbeak",
    scientificName: "Pheucticus melanocephalus",
    region: "Western North America",
    habitat: "Woodland and forest edge",
    wikiTitle: "Black-headed grosbeak",
  },
  {
    slug: "cedar-waxwing",
    name: "Cedar Waxwing",
    scientificName: "Bombycilla cedrorum",
    region: "North America",
    habitat: "Open woodland and fruiting trees",
    wikiTitle: "Cedar waxwing",
  },
  // Bee-eaters, rollers, kingfishers, motmots
  {
    slug: "european-bee-eater",
    name: "European Bee-eater",
    scientificName: "Merops apiaster",
    region: "Southern Europe and Africa",
    habitat: "Open country and sandy banks",
    wikiTitle: "European bee-eater",
  },
  {
    slug: "blue-throated-bee-eater",
    name: "Blue-throated Bee-eater",
    scientificName: "Merops viridis",
    region: "Southeast Asia",
    habitat: "Open country and forest edge",
    wikiTitle: "Blue-throated bee-eater",
  },
  {
    slug: "southern-carmine-bee-eater",
    name: "Southern Carmine Bee-eater",
    scientificName: "Merops nubicoides",
    region: "Southern Africa",
    habitat: "Savanna and riverbanks",
    wikiTitle: "Southern carmine bee-eater",
  },
  {
    slug: "european-roller",
    name: "European Roller",
    scientificName: "Coracias garrulus",
    region: "Europe and Africa",
    habitat: "Open woodland and farmland",
    wikiTitle: "European roller",
  },
  {
    slug: "indian-roller",
    name: "Indian Roller",
    scientificName: "Coracias benghalensis",
    region: "South Asia",
    habitat: "Open grassland and farmland",
    wikiTitle: "Indian roller",
  },
  {
    slug: "belted-kingfisher",
    name: "Belted Kingfisher",
    scientificName: "Megaceryle alcyon",
    region: "North America",
    habitat: "Rivers, lakes, and coastlines",
    wikiTitle: "Belted kingfisher",
  },
  {
    slug: "sacred-kingfisher",
    name: "Sacred Kingfisher",
    scientificName: "Todiramphus sanctus",
    region: "Australasia",
    habitat: "Forests, rivers, and coasts",
    wikiTitle: "Sacred kingfisher",
  },
  {
    slug: "white-throated-kingfisher",
    name: "White-throated Kingfisher",
    scientificName: "Halcyon smyrnensis",
    region: "South and Southeast Asia",
    habitat: "Open country near water",
    wikiTitle: "White-throated kingfisher",
  },
  {
    slug: "stork-billed-kingfisher",
    name: "Stork-billed Kingfisher",
    scientificName: "Pelargopsis capensis",
    region: "South and Southeast Asia",
    habitat: "Mangroves and forest streams",
    wikiTitle: "Stork-billed kingfisher",
  },
  {
    slug: "azure-kingfisher",
    name: "Azure Kingfisher",
    scientificName: "Ceyx azureus",
    region: "Australia and New Guinea",
    habitat: "Forest streams and mangroves",
    wikiTitle: "Azure kingfisher",
  },
  {
    slug: "turquoise-browed-motmot",
    name: "Turquoise-browed Motmot",
    scientificName: "Eumomota superciliosa",
    region: "Central America",
    habitat: "Open woodland and scrub",
    wikiTitle: "Turquoise-browed motmot",
  },
  {
    slug: "blue-crowned-motmot",
    name: "Blue-crowned Motmot",
    scientificName: "Momotus momota",
    region: "Central and South America",
    habitat: "Rainforest and woodland",
    wikiTitle: "Blue-crowned motmot",
  },
  // Hornbills & owls
  {
    slug: "southern-yellow-billed-hornbill",
    name: "Southern Yellow-billed Hornbill",
    scientificName: "Tockus leucomelas",
    region: "Southern Africa",
    habitat: "Dry savanna and thorn scrub",
    wikiTitle: "Southern yellow-billed hornbill",
  },
  {
    slug: "rhinoceros-hornbill",
    name: "Rhinoceros Hornbill",
    scientificName: "Buceros rhinoceros",
    region: "Southeast Asia",
    habitat: "Lowland rainforest",
    wikiTitle: "Rhinoceros hornbill",
  },
  {
    slug: "great-hornbill",
    name: "Great Hornbill",
    scientificName: "Buceros bicornis",
    region: "South and Southeast Asia",
    habitat: "Evergreen and deciduous forest",
    wikiTitle: "Great hornbill",
  },
  {
    slug: "malabar-pied-hornbill",
    name: "Malabar Pied Hornbill",
    scientificName: "Anthracoceros coronatus",
    region: "Indian subcontinent",
    habitat: "Moist deciduous forest",
    wikiTitle: "Malabar pied hornbill",
  },
  {
    slug: "snowy-owl",
    name: "Snowy Owl",
    scientificName: "Bubo scandiacus",
    region: "Arctic tundra",
    habitat: "Open tundra and coastal fields",
    wikiTitle: "Snowy owl",
  },
  {
    slug: "barn-owl",
    name: "Barn Owl",
    scientificName: "Tyto alba",
    region: "Worldwide",
    habitat: "Farmland, grassland, and open woodland",
    wikiTitle: "Barn owl",
  },
  {
    slug: "great-grey-owl",
    name: "Great Grey Owl",
    scientificName: "Strix nebulosa",
    region: "Northern Hemisphere boreal forest",
    habitat: "Taiga and montane forest",
    wikiTitle: "Great grey owl",
  },
  // Raptors
  {
    slug: "bald-eagle",
    name: "Bald Eagle",
    scientificName: "Haliaeetus leucocephalus",
    region: "North America",
    habitat: "Lakes, rivers, and coasts",
    wikiTitle: "Bald eagle",
  },
  {
    slug: "golden-eagle",
    name: "Golden Eagle",
    scientificName: "Aquila chrysaetos",
    region: "Northern Hemisphere",
    habitat: "Mountains, moorland, and open country",
    wikiTitle: "Golden eagle",
  },
  {
    slug: "peregrine-falcon",
    name: "Peregrine Falcon",
    scientificName: "Falco peregrinus",
    region: "Worldwide",
    habitat: "Cliffs, cities, and open country",
    wikiTitle: "Peregrine falcon",
  },
  {
    slug: "american-kestrel",
    name: "American Kestrel",
    scientificName: "Falco sparverius",
    region: "Americas",
    habitat: "Open country and farmland",
    wikiTitle: "American kestrel",
  },
  // Fairywrens & birds-of-paradise
  {
    slug: "superb-fairywren",
    name: "Superb Fairywren",
    scientificName: "Malurus cyaneus",
    region: "Southeastern Australia",
    habitat: "Scrubland and suburban gardens",
    wikiTitle: "Superb fairywren",
  },
  {
    slug: "splendid-fairywren",
    name: "Splendid Fairywren",
    scientificName: "Malurus splendens",
    region: "Australia",
    habitat: "Arid scrub and woodland",
    wikiTitle: "Splendid fairywren",
  },
  {
    slug: "wilsons-bird-of-paradise",
    name: "Wilson's Bird-of-paradise",
    scientificName: "Diphyllodes respublica",
    region: "West Papua",
    habitat: "Hill rainforest",
    wikiTitle: "Wilson's bird-of-paradise",
  },
  {
    slug: "red-bird-of-paradise",
    name: "Red Bird-of-paradise",
    scientificName: "Paradisaea rubra",
    region: "Indonesia",
    habitat: "Lowland rainforest",
    wikiTitle: "Red bird-of-paradise",
  },
  {
    slug: "king-bird-of-paradise",
    name: "King Bird-of-paradise",
    scientificName: "Cicinnurus regius",
    region: "New Guinea",
    habitat: "Lowland rainforest",
    wikiTitle: "King bird-of-paradise",
  },
  {
    slug: "victorias-riflebird",
    name: "Victoria's Riflebird",
    scientificName: "Ptiloris victoriae",
    region: "Northeastern Australia",
    habitat: "Rainforest",
    wikiTitle: "Victoria's riflebird",
  },
  {
    slug: "superb-bird-of-paradise",
    name: "Superb Bird-of-paradise",
    scientificName: "Lophorina superba",
    region: "New Guinea",
    habitat: "Montane rainforest",
    wikiTitle: "Superb bird-of-paradise",
  },
  {
    slug: "lesser-bird-of-paradise",
    name: "Lesser Bird-of-paradise",
    scientificName: "Paradisaea minor",
    region: "New Guinea",
    habitat: "Lowland rainforest",
    wikiTitle: "Lesser bird-of-paradise",
  },
  {
    slug: "raggiana-bird-of-paradise",
    name: "Raggiana Bird-of-paradise",
    scientificName: "Paradisaea raggiana",
    region: "New Guinea",
    habitat: "Tropical rainforest",
    wikiTitle: "Raggiana bird-of-paradise",
  },
  {
    slug: "twelve-wired-bird-of-paradise",
    name: "Twelve-wired Bird-of-paradise",
    scientificName: "Seleucidis melanoleucus",
    region: "New Guinea",
    habitat: "Lowland swamp forest",
    wikiTitle: "Twelve-wired bird-of-paradise",
  },
  // Penguins & ratites
  {
    slug: "king-penguin",
    name: "King Penguin",
    scientificName: "Aptenodytes patagonicus",
    region: "Subantarctic islands",
    habitat: "Rocky coasts and beaches",
    wikiTitle: "King penguin",
  },
  {
    slug: "emperor-penguin",
    name: "Emperor Penguin",
    scientificName: "Aptenodytes forsteri",
    region: "Antarctica",
    habitat: "Sea ice and coastal colonies",
    wikiTitle: "Emperor penguin",
  },
  {
    slug: "adelie-penguin",
    name: "Adélie Penguin",
    scientificName: "Pygoscelis adeliae",
    region: "Antarctica",
    habitat: "Rocky Antarctic coasts",
    wikiTitle: "Adélie penguin",
  },
  {
    slug: "gentoo-penguin",
    name: "Gentoo Penguin",
    scientificName: "Pygoscelis papua",
    region: "Subantarctic and Antarctic Peninsula",
    habitat: "Coastal colonies",
    wikiTitle: "Gentoo penguin",
  },
  {
    slug: "southern-rockhopper-penguin",
    name: "Southern Rockhopper Penguin",
    scientificName: "Eudyptes chrysocome",
    region: "Subantarctic islands",
    habitat: "Rocky coasts and cliffs",
    wikiTitle: "Southern rockhopper penguin",
  },
  {
    slug: "southern-cassowary",
    name: "Southern Cassowary",
    scientificName: "Casuarius casuarius",
    region: "New Guinea and Australia",
    habitat: "Tropical rainforest",
    wikiTitle: "Southern cassowary",
  },
  // Wading birds & cranes
  {
    slug: "scarlet-ibis",
    name: "Scarlet Ibis",
    scientificName: "Eudocimus ruber",
    region: "South America and Caribbean",
    habitat: "Mangroves, mudflats, and wetlands",
    wikiTitle: "Scarlet ibis",
  },
  {
    slug: "roseate-spoonbill",
    name: "Roseate Spoonbill",
    scientificName: "Platalea ajaja",
    region: "Americas",
    habitat: "Shallow wetlands and mangroves",
    wikiTitle: "Roseate spoonbill",
  },
  {
    slug: "american-flamingo",
    name: "American Flamingo",
    scientificName: "Phoenicopterus ruber",
    region: "Caribbean and Galápagos",
    habitat: "Saline lagoons and mudflats",
    wikiTitle: "American flamingo",
  },
  {
    slug: "chilean-flamingo",
    name: "Chilean Flamingo",
    scientificName: "Phoenicopterus chilensis",
    region: "South America",
    habitat: "Salt lakes and estuaries",
    wikiTitle: "Chilean flamingo",
  },
  {
    slug: "purple-gallinule",
    name: "Purple Gallinule",
    scientificName: "Porphyrio martinicus",
    region: "Americas",
    habitat: "Freshwater marshes and lily pads",
    wikiTitle: "Purple gallinule",
  },
  {
    slug: "purple-swamphen",
    name: "Purple Swamphen",
    scientificName: "Porphyrio porphyrio",
    region: "Europe, Africa, Asia, and Australasia",
    habitat: "Wetlands and reed beds",
    wikiTitle: "Western swamphen",
    imageUrl:
      "https://upload.wikimedia.org/wikipedia/commons/6/6c/Purpurhuhn.jpg",
  },
  {
    slug: "grey-crowned-crane",
    name: "Grey Crowned Crane",
    scientificName: "Balearica regulorum",
    region: "East and Southern Africa",
    habitat: "Wetlands, grassland, and savanna",
    wikiTitle: "Grey crowned crane",
  },
  {
    slug: "red-crowned-crane",
    name: "Red-crowned Crane",
    scientificName: "Grus japonensis",
    region: "East Asia",
    habitat: "Marshes and wet meadows",
    wikiTitle: "Red-crowned crane",
  },
  {
    slug: "sandhill-crane",
    name: "Sandhill Crane",
    scientificName: "Antigone canadensis",
    region: "North America",
    habitat: "Wetlands, prairies, and tundra",
    wikiTitle: "Sandhill crane",
  },
  // Hummingbirds
  {
    slug: "annas-hummingbird",
    name: "Anna's Hummingbird",
    scientificName: "Calypte anna",
    region: "Western North America",
    habitat: "Gardens, chaparral, and woodland",
    wikiTitle: "Anna's hummingbird",
  },
  {
    slug: "ruby-throated-hummingbird",
    name: "Ruby-throated Hummingbird",
    scientificName: "Archilochus colubris",
    region: "Eastern North America",
    habitat: "Gardens and deciduous forest",
    wikiTitle: "Ruby-throated hummingbird",
  },
  {
    slug: "violet-crowned-hummingbird",
    name: "Violet-crowned Hummingbird",
    scientificName: "Leucolia violiceps",
    region: "Southwestern North America",
    habitat: "Riparian woodland and sycamore groves",
    wikiTitle: "Violet-crowned hummingbird",
  },
  {
    slug: "sword-billed-hummingbird",
    name: "Sword-billed Hummingbird",
    scientificName: "Ensifera ensifera",
    region: "Andes of South America",
    habitat: "Montane forest and páramo",
    wikiTitle: "Sword-billed hummingbird",
  },
  {
    slug: "fiery-throated-hummingbird",
    name: "Fiery-throated Hummingbird",
    scientificName: "Panterpe insignis",
    region: "Costa Rica and Panama highlands",
    habitat: "Cloud forest and páramo edge",
    wikiTitle: "Fiery-throated hummingbird",
  },
  {
    slug: "blue-throated-mountaingem",
    name: "Blue-throated Mountain-gem",
    scientificName: "Lampornis clemenciae",
    region: "Mexico and Central America",
    habitat: "Montane pine-oak forest",
    wikiTitle: "Blue-throated mountaingem",
  },
  // Corvids & jays
  {
    slug: "green-jay",
    name: "Green Jay",
    scientificName: "Cyanocorax luxuosus",
    region: "Central America and Mexico",
    habitat: "Subtropical forest and scrub",
    wikiTitle: "Green jay",
  },
  {
    slug: "stellers-jay",
    name: "Steller's Jay",
    scientificName: "Cyanocitta stelleri",
    region: "Western North America",
    habitat: "Conifer and mixed forest",
    wikiTitle: "Steller's jay",
  },
  {
    slug: "eurasian-jay",
    name: "Eurasian Jay",
    scientificName: "Garrulus glandarius",
    region: "Europe and Asia",
    habitat: "Deciduous and mixed forest",
    wikiTitle: "Eurasian jay",
  },
  {
    slug: "taiwan-blue-magpie",
    name: "Taiwan Blue Magpie",
    scientificName: "Urocissa caerulea",
    region: "Taiwan",
    habitat: "Broadleaf forest and scrub",
    wikiTitle: "Taiwan blue magpie",
  },
  {
    slug: "red-billed-blue-magpie",
    name: "Red-billed Blue Magpie",
    scientificName: "Urocissa erythroryncha",
    region: "East and Southeast Asia",
    habitat: "Forest and scrubland",
    wikiTitle: "Red-billed blue magpie",
  },
  // Finches & starlings
  {
    slug: "european-goldfinch",
    name: "European Goldfinch",
    scientificName: "Carduelis carduelis",
    region: "Europe, North Africa, and Western Asia",
    habitat: "Open country with thistles and weeds",
    wikiTitle: "European goldfinch",
  },
  {
    slug: "eurasian-bullfinch",
    name: "Eurasian Bullfinch",
    scientificName: "Pyrrhula pyrrhula",
    region: "Europe and Asia",
    habitat: "Woodland, orchards, and gardens",
    wikiTitle: "Eurasian bullfinch",
  },
  {
    slug: "pine-grosbeak",
    name: "Pine Grosbeak",
    scientificName: "Pinicola enucleator",
    region: "Northern conifer forests",
    habitat: "Spruce and pine woodland",
    wikiTitle: "Pine grosbeak",
  },
  {
    slug: "gouldian-finch",
    name: "Gouldian Finch",
    scientificName: "Chloebia gouldiae",
    region: "Northern Australia",
    habitat: "Tropical savanna woodland",
    wikiTitle: "Gouldian finch",
  },
  {
    slug: "zebra-finch",
    name: "Zebra Finch",
    scientificName: "Taeniopygia guttata",
    region: "Australia",
    habitat: "Dry grassland and scrub",
    wikiTitle: "Zebra finch",
  },
  {
    slug: "violet-backed-starling",
    name: "Violet-backed Starling",
    scientificName: "Cinnyricinclus leucogaster",
    region: "Sub-Saharan Africa",
    habitat: "Open woodland and savanna",
    wikiTitle: "Violet-backed starling",
  },
  {
    slug: "golden-breasted-starling",
    name: "Golden-breasted Starling",
    scientificName: "Cosmopsarus regius",
    region: "East Africa",
    habitat: "Dry thorn scrub and savanna",
    wikiTitle: "Golden-breasted starling",
  },
  // Australasia & misc
  {
    slug: "laughing-kookaburra",
    name: "Laughing Kookaburra",
    scientificName: "Dacelo novaeguineae",
    region: "Eastern Australia",
    habitat: "Eucalypt forest and open woodland",
    wikiTitle: "Laughing kookaburra",
  },
  {
    slug: "tawny-frogmouth",
    name: "Tawny Frogmouth",
    scientificName: "Podargus strigoides",
    region: "Australia and Tasmania",
    habitat: "Woodland and urban trees",
    wikiTitle: "Tawny frogmouth",
  },
  {
    slug: "hoatzin",
    name: "Hoatzin",
    scientificName: "Opisthocomus hoazin",
    region: "Amazon and Orinoco basins",
    habitat: "Riverine forest and mangroves",
    wikiTitle: "Hoatzin",
  },
  {
    slug: "scarlet-honeyeater",
    name: "Scarlet Honeyeater",
    scientificName: "Myzomela sanguinolenta",
    region: "Eastern Australia",
    habitat: "Forest and heathland",
    wikiTitle: "Scarlet honeyeater",
  },
  {
    slug: "crimson-chat",
    name: "Crimson Chat",
    scientificName: "Epthianura tricolor",
    region: "Australia",
    habitat: "Arid scrub and grassland",
    wikiTitle: "Crimson chat",
  },
  {
    slug: "common-hill-myna",
    name: "Common Hill Myna",
    scientificName: "Gracula religiosa",
    region: "South and Southeast Asia",
    habitat: "Forest and plantations",
    wikiTitle: "Common hill myna",
  },
  {
    slug: "satin-bowerbird",
    name: "Satin Bowerbird",
    scientificName: "Ptilonorhynchus violaceus",
    region: "Eastern Australia",
    habitat: "Rainforest and wet sclerophyll",
    wikiTitle: "Satin bowerbird",
  },
  {
    slug: "regent-bowerbird",
    name: "Regent Bowerbird",
    scientificName: "Sericulus chrysocephalus",
    region: "Eastern Australia",
    habitat: "Subtropical rainforest",
    wikiTitle: "Regent bowerbird",
  },
  {
    slug: "scarlet-minivet",
    name: "Scarlet Minivet",
    scientificName: "Pericrocotus speciosus",
    region: "South and Southeast Asia",
    habitat: "Forest and forest edge",
    wikiTitle: "Scarlet minivet",
  },
  {
    slug: "eurasian-golden-oriole",
    name: "Eurasian Golden Oriole",
    scientificName: "Oriolus oriolus",
    region: "Europe and Asia",
    habitat: "Deciduous forest and orchards",
    wikiTitle: "Eurasian golden oriole",
  },
  {
    slug: "black-naped-oriole",
    name: "Black-naped Oriole",
    scientificName: "Oriolus chinensis",
    region: "East and Southeast Asia",
    habitat: "Open woodland and gardens",
    wikiTitle: "Black-naped oriole",
  },
  // Herons & egrets
  {
    slug: "great-egret",
    name: "Great Egret",
    scientificName: "Ardea alba",
    region: "Worldwide tropics and temperate zones",
    habitat: "Wetlands, marshes, and shores",
    wikiTitle: "Great egret",
  },
  {
    slug: "little-blue-heron",
    name: "Little Blue Heron",
    scientificName: "Egretta caerulea",
    region: "Americas",
    habitat: "Marshes, ponds, and mangroves",
    wikiTitle: "Little blue heron",
  },
  {
    slug: "tricolored-heron",
    name: "Tricolored Heron",
    scientificName: "Egretta tricolor",
    region: "Americas",
    habitat: "Coastal marshes and lagoons",
    wikiTitle: "Tricolored heron",
  },
  {
    slug: "green-broadbill",
    name: "Green Broadbill",
    scientificName: "Calyptomena viridis",
    region: "Southeast Asia",
    habitat: "Lowland rainforest",
    wikiTitle: "Green broadbill",
  },
  {
    slug: "crimson-sunbird",
    name: "Crimson Sunbird",
    scientificName: "Aethopyga siparaja",
    region: "South and Southeast Asia",
    habitat: "Forest edge and gardens",
    wikiTitle: "Crimson sunbird",
  },
  {
    slug: "collared-kingfisher",
    name: "Collared Kingfisher",
    scientificName: "Todiramphus chloris",
    region: "Asia to Australasia",
    habitat: "Coasts, mangroves, and gardens",
    wikiTitle: "Collared kingfisher",
  },
  {
    slug: "secretarybird",
    name: "Secretarybird",
    scientificName: "Sagittarius serpentarius",
    region: "Sub-Saharan Africa",
    habitat: "Open grassland and savanna",
    wikiTitle: "Secretarybird",
  },
  {
    slug: "shoebill",
    name: "Shoebill",
    scientificName: "Balaeniceps rex",
    region: "Central Africa",
    habitat: "Papyrus swamps and wetlands",
    wikiTitle: "Shoebill",
  },
  {
    slug: "rufous-motmot",
    name: "Rufous Motmot",
    scientificName: "Baryphthengus martii",
    region: "Central America",
    habitat: "Rainforest understory",
    wikiTitle: "Rufous motmot",
  },
  {
    slug: "violet-crowned-woodnymph",
    name: "Violet-crowned Woodnymph",
    scientificName: "Thalurania colombica",
    region: "Central America and Colombia",
    habitat: "Humid forest and gardens",
    wikiTitle: "Violet-crowned woodnymph",
  },
  {
    slug: "andean-cock-of-the-rock",
    name: "Andean Cock-of-the-rock",
    scientificName: "Rupicola peruvianus",
    region: "Andes of South America",
    habitat: "Cloud forest ravines",
    wikiTitle: "Andean cock-of-the-rock",
  },
  {
    slug: "guianan-cock-of-the-rock",
    name: "Guianan Cock-of-the-rock",
    scientificName: "Rupicola rupicola",
    region: "Northern South America",
    habitat: "Rocky forest streams",
    wikiTitle: "Guianan cock-of-the-rock",
  },
  {
    slug: "horned-sungem",
    name: "Horned Sungem",
    scientificName: "Heliactin bilophus",
    region: "South America",
    habitat: "Cerrado and open woodland",
    wikiTitle: "Horned sungem",
  },
  {
    slug: "spangled-cotinga",
    name: "Spangled Cotinga",
    scientificName: "Cotinga cayana",
    region: "Amazon basin",
    habitat: "Rainforest canopy",
    wikiTitle: "Spangled cotinga",
  },
  {
    slug: "plum-throated-cotinga",
    name: "Plum-throated Cotinga",
    scientificName: "Cotinga maynana",
    region: "Amazon basin",
    habitat: "Flooded forest canopy",
    wikiTitle: "Plum-throated cotinga",
  },
  {
    slug: "scarlet-chested-sunbird",
    name: "Scarlet-chested Sunbird",
    scientificName: "Chalcomitra senegalensis",
    region: "Sub-Saharan Africa",
    habitat: "Savanna and woodland",
    wikiTitle: "Scarlet-chested sunbird",
  },
  {
    slug: "malachite-kingfisher",
    name: "Malachite Kingfisher",
    scientificName: "Corythornis cristatus",
    region: "Sub-Saharan Africa",
    habitat: "Reeds and slow waterways",
    wikiTitle: "Malachite kingfisher",
  },
];
